version: 2
ethernets:
  eth0:
    dhcp4: false
    addresses:
      - 10.1.2.101/24
    nameservers:
      search:
        - nsb.local
      addresses:
        - 10.1.2.5
    routes:
      - to: 0.0.0.0/0
        via: 10.1.2.1
        metric: 10
