version: 2
ethernets:
  eth0:
    addresses: [ "10.1.2.101/24" ]
    nameservers:
      addresses: [ "10.1.2.5" ]
    search: [ "nsb.local" ]
    routes:
    - to: 0.0.0.0/0
      via: 10.1.2.1
      metric: 10
