---
imports:
  networks: !- $import('networks.yaml')
  params: !? $import('config-params.yaml')
misc:
  networks: !? .imports.networks.networks
hosts:
  generators:
    nameservers: &nameservers !? $_.imports.params.nameservers

    infra_nodes: !-
      items: !-
        - name: jump-host
          hostname: jump-host
          fqdn: jump-host.nsb.local
          network_1: !? .misc.networks.where($.name = 'management-network-' + $env.SITE_NAME).first()
          address_1: !? $_.imports.params.hosts.jump_host.address_1
          eth_index: 0
          eth_prefix: eth
          eth_suffix: ''
          group: wheel
        - name: nginx-lb-host
          hostname: nginx-lb-host
          fqdn: nginx-lb-host.nsb.local
          network_1: !? .misc.networks.where($.name = 'gw-frontend-network-' + $env.SITE_NAME).first()
          address_1: !? $_.imports.params.hosts.nginx_lb_host.address_1
          network_2: !? .misc.networks.where($.name = 'gw-backend-network-' + $env.SITE_NAME).first()
          address_2: !? $_.imports.params.hosts.nginx_lb_host.address_2
          eth_index: 1
          eth_prefix: enp
          eth_suffix: s0
          group: sudo
        - name: dns-host
          hostname: dns-host
          fqdn: dns-host.nsb.local
          network_1: !? .misc.networks.where($.name = 'management-network-' + $env.SITE_NAME).first()
          address_1: !? $_.imports.params.hosts.dns_host.address_1
          eth_index: 1
          eth_prefix: enp
          eth_suffix: s0
          group: sudo

    datapower: !-
      items:
        - ? !for "sequence().take(3)"
          : !()
            - name: !? '"datapower-{0}".format($+1)'
              hostname: !? '"pr-apic-dpgw{0}".format($+1)'
              fqdn: !? '"pr-apic-dpgw{0}.nsb.local".format($+1)'
              address_1: !? '"{0}.{1}/25".format($_.imports.params.hosts.datapower.network_1_prefix, $+11)'
              address_2: !? '"{0}.{1}/25".format($_.imports.params.hosts.datapower.network_1_prefix, $+139)'
              network_1: !? .misc.networks.where($.name = 'gw-frontend-network-' + $env.SITE_NAME).first()
              network_2: !? .misc.networks.where($.name = 'gw-backend-network-' + $env.SITE_NAME).first()
              eth_index: 0
              eth_prefix: eth
              eth_suffix: ''
              group: wheel

    nodes:
      items: !? $_.hosts.generators.infra_nodes.items.concat($_.hosts.generators.datapower.items)
      hosts:
        - ? !for $_.hosts.generators.nodes.items
          : !()
            - cloud_config:
                hostname: !? $.hostname
                fqdn: !? $.fqdn
                users:
                  - default
                  - name: root
                    ssh_authorized_keys:
                      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCk4kiMZEZl6xXf21wNR0wxLtno4TmpruZoDqjFn5+s4DY2ahjVeBirICB01Dj3h8RgG+ggxMU3VdhvwZjb5HiVeAvxtrRlaAtPfjxZBju1Wtlge/Lg5EKPcY79ZNiGOiuiSgHuKW99hypp0hBNzW1Skln4A4nUOHDBW4qQzv5k0Il8GN/JcLfq93mWkTkPPyXN3JsBmCS+eo37wixIS3ESQr+SfhCkRBFK/Ll0NiQbtpWbVcsoWHGD5KMuAIHlVvBW1fydemNJnm2C3Drbta7dQC5oHJ6NcgC88TK9nzQX10vc19xl5eVPX9XDvlZWebvQOMh//rkWnYkKY1FUHLufrWxZPWAK3Y6w5904FimDDMZCvY8LS2gwmolMacWMHtixs96/n7SpO/mOAsOgeOJikZ4cFeHa6Ec9RwJvnt2Y7o9dbPhCX3bzgJBBA8cmbFthqrSdyEGRD7vCbdR3FKZyju6EZSRK2Niy40uZDtWFMH09N0Za8THJxeWRAaJly0N4D/n+KC1yo3G9JK21fs70ZUhVf8MP+RKBFoBglTrsgh/owPlKAuO12gw/ULItj/Q9MC0HxlIFBPDg46PSvfntVhQ682SgoZaFVTsQOvEcv6TXE8Pu/H4A4DLtVXDv060OUowJLb1fEQny4NmIr5VVyPnpS07aERDwdibsMx/oUQ== iresh@kvm-host
                  - name: iresh
                    gecos: Iresh Dissanayaka
                    groups: !? $.group
                    shell: /bin/bash
                    plain_text_passwd: admin123
                    lock_passwd: false
                    ssh_authorized_keys:
                      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCk4kiMZEZl6xXf21wNR0wxLtno4TmpruZoDqjFn5+s4DY2ahjVeBirICB01Dj3h8RgG+ggxMU3VdhvwZjb5HiVeAvxtrRlaAtPfjxZBju1Wtlge/Lg5EKPcY79ZNiGOiuiSgHuKW99hypp0hBNzW1Skln4A4nUOHDBW4qQzv5k0Il8GN/JcLfq93mWkTkPPyXN3JsBmCS+eo37wixIS3ESQr+SfhCkRBFK/Ll0NiQbtpWbVcsoWHGD5KMuAIHlVvBW1fydemNJnm2C3Drbta7dQC5oHJ6NcgC88TK9nzQX10vc19xl5eVPX9XDvlZWebvQOMh//rkWnYkKY1FUHLufrWxZPWAK3Y6w5904FimDDMZCvY8LS2gwmolMacWMHtixs96/n7SpO/mOAsOgeOJikZ4cFeHa6Ec9RwJvnt2Y7o9dbPhCX3bzgJBBA8cmbFthqrSdyEGRD7vCbdR3FKZyju6EZSRK2Niy40uZDtWFMH09N0Za8THJxeWRAaJly0N4D/n+KC1yo3G9JK21fs70ZUhVf8MP+RKBFoBglTrsgh/owPlKAuO12gw/ULItj/Q9MC0HxlIFBPDg46PSvfntVhQ682SgoZaFVTsQOvEcv6TXE8Pu/H4A4DLtVXDv060OUowJLb1fEQny4NmIr5VVyPnpS07aERDwdibsMx/oUQ== iresh@kvm-host
                !if $.name.startsWith('datapower'):
                  runcmd:
                      -
                        - sh
                        - -c
                        - 'sed -i s/BOOTPROTO=dhcp/BOOTPROTO=static/ /etc/sysconfig/network-scripts/ifcfg-eth*'
                      -
                        - sh
                        - -c
                        - 'echo "1    rt2" >> /etc/iproute2/rt_tables'
                      -
                        - sh
                        - -c
                        - !? '"echo \"default via {0} table rt2\" > /etc/sysconfig/network-scripts/route-eth0".format($.network_1.gateway)'
                      -
                        - sh
                        - -c
                        - !? '"echo -e \"from {0} table rt2\\nto {1}/{2} table rt2\" > /etc/sysconfig/network-scripts/rule-eth0".format($.network_1.address, $.network_1.address, $.network_1.suffix)'
                      -
                        - sh
                        - -c
                        - 'ifdown eth0 && sleep 1 && ifup eth0 && sleep 1 && ip a'
                      -
                        - sh
                        - -c
                        - 'ifdown eth1 && sleep 1 && ifup eth1 && sleep 1 && ip a'
              network_config:
                version: 2
                ethernets:
                  !? '"{0}{1}{2}".format($.eth_prefix, $.eth_index + 0, $.eth_suffix)':
                    dhcp4: false
                    addresses:
                      - !? $.address_1
                    nameservers:
                      search: [ "nsb.local" ]
                      !if not $.name.startsWith('dns-host'):
                        addresses: *nameservers
                      !if $.name.startsWith('dns-host'):
                        addresses:
                          - '8.8.8.8'
                    routes:
                    - to: 0.0.0.0/0
                      via: !? $.network_1.gateway
                      metric: 10
                  !if $.containsKey('network_2'):
                    !? '"{0}{1}{2}".format($.eth_prefix, $.eth_index + 1, $.eth_suffix)':
                      dhcp4: false
                      addresses:
                        - !? $.address_2
                      nameservers:
                        search: [ "nsb.local" ]
                        addresses: *nameservers
                      routes:
                      - to: 0.0.0.0/0
                        via: !? $.network_2.gateway
                        metric: 10
